### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Lampe96** [softwaremill/fablo-rest#39]
I've correctly installed the fablo-rest but when i'm trying to enroll a new user the error "Curl: (7) Failed to connect to localhost port 8000: connection refused".

I'm leaving here the enroll request and the docker-compose.yaml settings:

```console
curl --request POST 
  --url http://localhost:8000/user/enroll 
  --header 'Authorization: Bearer' 
  --data '{"id": "admin", "secret": "adminpw"}'
```

```yaml
fablo-rest.home1.project.it:
    container_name: fablo-rest.home1.project.it
    image: softwaremill/fablo-rest:${FABLO_REST_VERSION}
    environment:
      - PORT=8000
      - MSP_ID=Home1MSP
      - FABRIC_CA_URL=http://ca.home1.project.it:7054/
      - FABRIC_CA_NAME=ca.home1.project.it
      - AS_LOCALHOST=false
      - DISCOVERY_URLS=grpcs://peer0.home1.project.it:7041,grpcs://peer1.home1.project.it:7042,grpcs://peer0.home2.project.it:7061,grpcs://peer1.home2.project.it:7062
      - DISCOVERY_SSL_TARGET_NAME_OVERRIDES=
      - DISCOVERY_TLS_CA_CERT_FILES=/crypto/home1.project.it/peers/peer0.home1.project.it/tls/ca.crt,/crypto/home1.project.it/peers/peer1.home1.project.it/tls/ca.crt,/crypto/home2.project.it/peers/peer0.home2.project.it/tls/ca.crt,/crypto/home2.project.it/peers/peer1.home2.project.it/tls/ca.crt
      - HFC_LOGGING={"error":"console","warn":"console","info":"console"}
    volumes:
      # note: fablo needs access to all anchor peer certs
      - ../fabric-config/crypto-config/peerOrganizations:/crypto:ro
    ports:
      - 8801:8000
    networks:
      - basic
```
